piVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-controller
spec:
  selector:
    matchLabels:
      application: skupper-controller
  template:
    spec:
      containers:
        - name: controller
          env:
            - name: RELATED_IMAGE_SKUPPER_CONTROLLER_IMAGE
              value: registry-proxy.engineering.redhat.com/rh-osbs/service-interconnect-controller-rhel9:2.0.0-3
            - name: RELATED_IMAGE_SKUPPER_ROUTER_IMAGE
              value: registry-proxy.engineering.redhat.com/rh-osbs/service-interconnect-skupper-router-rhel9:3.2.0-1              
            - name: RELATED_IMAGE_SKUPPER_KUBE_ADAPTOR_IMAGE
              value: registry-proxy.engineering.redhat.com/rh-osbs/service-interconnect-kube-adaptor-rhel9:2.0.0-1
            - name: RELATED_IMAGE_SKUPPER_NETWORK_OBSERVER_IMAGE
              value: registry-proxy.engineering.redhat.com/rh-osbs/service-interconnect-network-observer-rhel9:2.0.0-1
            - name: RELATED_IMAGE_SKUPPER_CLI_IMAGE
              value: registry-proxy.engineering.redhat.com/rh-osbs/service-interconnect-cli-rhel9:2.0.0-1                                          
            - name: SKUPPER_KUBE_ADAPTOR_IMAGE
              value: registry-proxy.engineering.redhat.com/rh-osbs/service-interconnect-kube-adaptor-rhel9:2.0.0-1
            - name: SKUPPER_KUBE_ADAPTOR_IMAGE_PULL_POLICY
              value: Always          
