apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: connectors.skupper.io
spec:
  group: skupper.io
  names:
    kind: Connector
    plural: connectors
    singular: connector
  scope: Namespaced
  versions:
  - additionalPrinterColumns:
    - description: The key that ties connectors and listeners together
      jsonPath: .spec.routingKey
      name: Routing Key
      type: string
    - description: The port to connect to
      jsonPath: .spec.port
      name: Port
      type: integer
    - description: The host to connect to
      jsonPath: .spec.host
      name: Host
      type: string
    - description: The selector that identifies the pods to connect to
      jsonPath: .spec.selector
      name: Selector
      type: string
    - description: The status of the connector
      jsonPath: .status.status
      name: Status
      type: string
    - description: Whether there is at least one listener in the network with a matching
        routing key.
      jsonPath: .status.hasMatchingListener
      name: Has Matching Listener
      type: boolean
    - description: Any human readable message relevant to the connector
      jsonPath: .status.message
      name: Message
      type: string
    name: v2alpha1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            oneOf:
            - required:
              - selector
            - required:
              - host
            properties:
              exposePodsByName:
                type: boolean
              host:
                type: string
              includeNotReadyPods:
                type: boolean
              port:
                type: integer
              routingKey:
                type: string
              selector:
                type: string
              settings:
                additionalProperties:
                  type: string
                type: object
              tlsCredentials:
                type: string
              type:
                type: string
              useClientCert:
                type: boolean
              verifyHostname:
                type: boolean
            required:
            - routingKey
            - port
            type: object
          status:
            properties:
              conditions:
                items:
                  properties:
                    lastTransitionTime:
                      format: date-time
                      type: string
                    message:
                      maxLength: 32768
                      type: string
                    observedGeneration:
                      format: int64
                      minimum: 0
                      type: integer
                    reason:
                      maxLength: 1024
                      minLength: 1
                      pattern: ^[A-Za-z]([A-Za-z0-9_,:]*[A-Za-z0-9_])?$
                      type: string
                    status:
                      enum:
                      - "True"
                      - "False"
                      - Unknown
                      type: string
                    type:
                      maxLength: 316
                      pattern: ^([a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*/)?(([A-Za-z0-9][-
                        A-Za-z0-9_.]*)?[A-Za-z0-9])$
                      type: string
                  required:
                  - lastTransitionTime
                  - message
                  - reason
                  - status
                  - type
                  type: object
                type: array
              hasMatchingListener:
                type: boolean
              message:
                type: string
              selectedPods:
                items:
                  properties:
                    ip:
                      type: string
                    name:
                      type: string
                  type: object
                type: array
              status:
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: null
  storedVersions: null
