apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    olm.skipRange: '>2.0.0-rh-rc0-1'
    certified: "false"
    categories: "Integration & Delivery, Networking, Streaming & Messaging"
    description: Red Hat Service Interconnect Operator provides the ability to create a service network
    containerImage: registry-proxy.engineering.redhat.com/rh-osbs/service-interconnect-controller-rhel9:2.0.0-3
    createdAt: 2021-04-14T08:00:00Z
    capabilities: Seamless Upgrades
    repository: https://github.com/skupperproject/skupper
    support: Red Hat
    operators.openshift.io/valid-subscription: '["Red Hat Service Interconnect"]'
    operators.openshift.io/infrastructure-features: '["disconnected"]'
    features.operators.openshift.io/disconnected: "true" # Specify whether an Operator leverages the spec.relatedImages CSV field and can run without an internet connection by referring to any related image by its digest.
    features.operators.openshift.io/fips-compliant: "false" # Specify whether an Operator accepts the FIPS-140 configuration of the underlying platform and works on nodes that are booted into FIPS mode. In this mode, the Operator and any workloads it manages (operands) are solely calling the Red Hat Enterprise Linux (RHEL) cryptographic library submitted for FIPS-140 validation.
    features.operators.openshift.io/proxy-aware: "false" # Specify whether an Operator supports running on a cluster behind a proxy by accepting the standard HTTP_PROXY and HTTPS_PROXY proxy environment variables. If applicable, the Operator passes this information to the workload it manages (operands).
    features.operators.openshift.io/tls-profiles: "false" # Specify whether an Operator implements well-known tunables to modify the TLS cipher suite used by the Operator and, if applicable, any of the workloads it manages (operands).
    features.operators.openshift.io/token-auth-aws: "false" # Specify whether an Operator supports configuration for tokenzied authentication with AWS APIs via AWS Secure Token Service (STS) by using the Cloud Credential Operator (CCO).
    features.operators.openshift.io/token-auth-azure: "false" # Specify whether an Operator supports configuration for tokenzied authentication with Azure APIs via Azure Managed Identity by using the Cloud Credential Operator (CCO).
    features.operators.openshift.io/token-auth-gcp: "false" # Specify whether an Operator supports configuration for tokenzied authentication with Google Cloud APIs via GCP Workload Identity Foundation (WIF) by using the Cloud Credential Operator (CCO).
    features.operators.openshift.io/cnf: "false" # Specify whether an Operator provides a Cloud-Native Network Function (CNF) Kubernetes plugin.
    features.operators.openshift.io/cni: "false" # Specify whether an Operator provides a Container Network Interface (CNI) Kubernetes plugin.
    features.operators.openshift.io/csi: "false" # Specify whether an Operator provides a Container Storage Interface (CSI) Kubernetes plugin.
    operators.operatorframework.io/builder: operator-sdk-v1.17.0+git
    operators.operatorframework.io/project_layout: go.kubebuilder.io/v3
  labels:
    operatorframework.io/os.linux: supported
    operatorframework.io/arch.amd64: supported
  name: skupper-operator.v2.0.0-rc1-rh-1
  namespace: placeholder
spec:
  replaces: skupper-operator.v2.0.0-rc0-rh-1
  apiservicedefinitions: {}
  description: |
    Red Hat Service Interconnect enables communication between services running in different network locations.
    It allows geographically distributed services to connect as if they were all running in the same site.

    Each site is a namespace with a running Red Hat Service Interconnect instance.

    The operator can only be installed at cluster level, watching for the skupper resources in all namespaces.
  displayName: Red Hat Service Interconnect
  icon:
  - base64data: PHN2ZyBpZD0iTGF5ZXJfMSIgZGF0YS1uYW1lPSJMYXllciAxIiB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCAxOTIgMTQ1Ij48ZGVmcz48c3R5bGU+LmNscy0xe2ZpbGw6I2UwMDt9PC9zdHlsZT48L2RlZnM+PHRpdGxlPlJlZEhhdC1Mb2dvLUhhdC1Db2xvcjwvdGl0bGU+PHBhdGggZD0iTTE1Ny43Nyw2Mi42MWExNCwxNCwwLDAsMSwuMzEsMy40MmMwLDE0Ljg4LTE4LjEsMTcuNDYtMzAuNjEsMTcuNDZDNzguODMsODMuNDksNDIuNTMsNTMuMjYsNDIuNTMsNDRhNi40Myw2LjQzLDAsMCwxLC4yMi0xLjk0bC0zLjY2LDkuMDZhMTguNDUsMTguNDUsMCwwLDAtMS41MSw3LjMzYzAsMTguMTEsNDEsNDUuNDgsODcuNzQsNDUuNDgsMjAuNjksMCwzNi40My03Ljc2LDM2LjQzLTIxLjc3LDAtMS4wOCwwLTEuOTQtMS43My0xMC4xM1oiLz48cGF0aCBjbGFzcz0iY2xzLTEiIGQ9Ik0xMjcuNDcsODMuNDljMTIuNTEsMCwzMC42MS0yLjU4LDMwLjYxLTE3LjQ2YTE0LDE0LDAsMCwwLS4zMS0zLjQybC03LjQ1LTMyLjM2Yy0xLjcyLTcuMTItMy4yMy0xMC4zNS0xNS43My0xNi42QzEyNC44OSw4LjY5LDEwMy43Ni41LDk3LjUxLjUsOTEuNjkuNSw5MCw4LDgzLjA2LDhjLTYuNjgsMC0xMS42NC01LjYtMTcuODktNS42LTYsMC05LjkxLDQuMDktMTIuOTMsMTIuNSwwLDAtOC40MSwyMy43Mi05LjQ5LDI3LjE2QTYuNDMsNi40MywwLDAsMCw0Mi41Myw0NGMwLDkuMjIsMzYuMywzOS40NSw4NC45NCwzOS40NU0xNjAsNzIuMDdjMS43Myw4LjE5LDEuNzMsOS4wNSwxLjczLDEwLjEzLDAsMTQtMTUuNzQsMjEuNzctMzYuNDMsMjEuNzdDNzguNTQsMTA0LDM3LjU4LDc2LjYsMzcuNTgsNTguNDlhMTguNDUsMTguNDUsMCwwLDEsMS41MS03LjMzQzIyLjI3LDUyLC41LDU1LC41LDc0LjIyYzAsMzEuNDgsNzQuNTksNzAuMjgsMTMzLjY1LDcwLjI4LDQ1LjI4LDAsNTYuNy0yMC40OCw1Ni43LTM2LjY1LDAtMTIuNzItMTEtMjcuMTYtMzAuODMtMzUuNzgiLz48L3N2Zz4=
    mediatype: image/svg+xml
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - skupper
  - service
  - mesh
  - van
  links:
  - name: Skupper Operator
    url: https://github.com/skupperproject/skupper-operator
  maintainers:
  - email: skupper@googlegroups.com
    name: Skupper Community
  maturity: stable
  minKubeVersion: 1.25.0
  provider:
    name: Skupper Project
    url: https://skupper.io
  relatedImages:
  - name: skupper-controller
    image: registry.redhat.io/service-interconnect/skupper-controller-rhel9@sha256:1234
  selector: {}
  version: 2.0.0-rc1
