apiVersion: apps/v1
kind: Deployment
metadata:
  name: skupper-controller
spec:
  selector:
    matchLabels:
      application: skupper-controller
  template:
    spec:
      containers:
        - name: controller
          env:
            - name: SKUPPER_KUBE_ADAPTOR_IMAGE
              value: registry.redhat.io/service-interconnect/skupper-kube-adaptor-rhel9@sha256:f256ea71c9f18e85170ef90ae2d46080a7e57174710e01f2418d6b6edadffaba
            - name: SKUPPER_KUBE_ADAPTOR_IMAGE_PULL_POLICY
              value: Always
            - name: SKUPPER_ROUTER_IMAGE
              value: registry.redhat.io/service-interconnect/skupper-router-rhel9@sha256:05dac819052db8c89b56d37d0f5385d51135dbad19310e7bba4c73d0ad78d081
            - name: SKUPPER_ROUTER_IMAGE_PULL_POLICY
              value: Always
